### ISSUE TITLE
Crash after picking a new challenge

### ISSUE THREAD

**Issue by hermansaksono** [WellnessLab/adc_caregiver#68]
1. Do a 7-day fitness challenge
2. Complete a challenge
3. Pick a new challenge
=> Crash

Stack trace:
```

02-23 10:20:49.502 26271-26271/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: edu.neu.ccs.wellness.adcaregiverapp, PID: 26271
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{edu.neu.ccs.wellness.adcaregiverapp/edu.neu.ccs.wellness.adcaregiverapp.presentation.MainActivity}: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                                                       at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                                                       at android.os.Handler.dispatchMessage(Handler.java:106)
                                                       at android.os.Looper.loop(Looper.java:164)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                    Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
                                                       at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2053)
                                                       at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2079)
                                                       at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:678)
                                                       at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:632)
                                                       at edu.neu.ccs.wellness.adcaregiverapp.presentation.MainActivity.navigateToCommunityGarden(MainActivity.java:284)
                                                       at edu.neu.ccs.wellness.adcaregiverapp.presentation.MainActivity.init(MainActivity.java:120)
                                                       at edu.neu.ccs.wellness.adcaregiverapp.presentation.MainActivity.onInternetConnectivityChanged(MainActivity.java:94)
                                                       at com.droidnet.DroidNet.publishInternetAvailabilityStatus(DroidNet.java:227)
                                                       at com.droidnet.DroidNet.addInternetConnectivityListener(DroidNet.java:96)
                                                       at edu.neu.ccs.wellness.adcaregiverapp.presentation.MainActivity.onCreate(MainActivity.java:77)
                                                       at android.app.Activity.performCreate(Activity.java:7009)
                                                       at android.app.Activity.performCreate(Activity.java:7000)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
                                                       at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                       at android.os.Looper.loop(Looper.java:164) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6494) 
```

**Comment by hermansaksono** [comment]
Fixed in PR 33
